### ISSUE TITLE
Warning: Failed to cancel https://github.com/pingcap/dm/actions/runs/766226952

### ISSUE THREAD

**Issue by lance6716** [fkirc/skip-duplicate-actions#103]
https://github.com/pingcap/dm/runs/2388157523?check_suite_focus=true

⬆️ This run says it wants to cancel https://github.com/pingcap/dm/actions/runs/766226952 but failed, left a warning. However I see the latter one is stuck in "Queued" status, seems the cancelation somehow taken effects. Is this expected?

**Comment by emabrey** [comment]
You may need to make sure that your repository settings are setup to make GITHUB_TOKEN restrictive.

Try adding this permission configuration to the build job you use to run this action:

```
permissions:
  actions: write
  checks: read
  contents: read
  deployments: read
  issues: read
  discussions: read
  packages: read
  pull-requests: read
  repository-projects: read
  security-events: read
  statuses: read
```
