### ISSUE TITLE
Skip: overlapping cron

### ISSUE THREAD

**Issue by splitice** [fkirc/skip-duplicate-actions#107]
What about supporting skipping of overlapping cron jobs?

What about supporting skipping of cron and commit overlapping?

**Comment by paescuj** [comment]
> What about supporting skipping of overlapping cron jobs?

Skipping newer jobs should be possible with the following configuration:
```yaml
          concurrent_skipping: 'same_content_newer'
          # Default is '["workflow_dispatch", "schedule"]'
          do_not_skip: '["workflow_dispatch"]'
```

> What about supporting skipping of cron and commit overlapping?

If triggers are defined in the same workflow, skipping newer jobs should work with the configuration from above.
