### ISSUE TITLE
Check commits outside pr

### ISSUE THREAD

**Issue by daixiang0** [fkirc/skip-duplicate-actions#122]
See https://github.com/dapr/cli/runs/2970646884?check_suite_focus=true

**Comment by fkirc** [comment]
I am not sure what this is about, more details might be needed.

**Comment by daixiang0** [comment]
There are two commits in the log:
```
Commit https://github.com/dapr/cli/commit/4e54707e77ff1c47cc9f2530668c739e89af0b85 is path-ignored: All of '.github/workflows/dapr_cli.yml,.github/workflows/installdaprwin.yml,.github/workflows/kind_e2e.yml,.github/workflows/release_notification.yml,.github/workflows/self_hosted_e2e.yml,.github/workflows/upgrade_e2e.yml' match against patterns '**.md,.codecov.yaml,.github/**/**.yml,CODEOWNERS'
Stop backtracking at commit https://github.com/dapr/cli/commit/0a37376658ef83e8a1b49178cf4e6f1c93eb1dfc because 'README.md,cmd/run.go,pkg/standalone/run.go,pkg/standalone/run_test.go' are not skippable against paths '' or paths_ignore '**.md,.codecov.yaml,.github/**/**.yml,CODEOWNERS'
```

While this pr only contains one.

**Comment by thadamski** [comment]
Love the action! I'm experiencing the same problem with commits being referenced outside of the scope of commits of my PR.

My PR against `develop` has a single commit "abc123", however, the output of my skip_check job is finding a matching changed file in a grandparent commit, "abc125", which is outside the scope of the PR.

Commit lineage:

abc123 <- Commit in my PR
abc124 <- HEAD of develop
abc125 <- Parent of HEAD of develop. This has a matching file change, but isn't in my PR

I have an action configured to run on on a `pull_request` trigger against my primary branch `develop`:

```yaml
name: My Action

on:
  pull_request:
    branches:
      - develop
  workflow_dispatch:

jobs:
  skip_check:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          paths: '["path/to/my/files/**"]'
          cancel_others: 'true'  # Cancel in progress run if new matching commit pushed after PR opened
  my-job:
    name: Some Job Name
    needs: skip_check
    if: ${{ needs.skip_check.outputs.should_skip != 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Do Something
        run: |
          echo "Doing something"
```
