### ISSUE TITLE
what is the equivalent syntax for skip_concurrent_trigger push in version 1.5.1 in the current version.

### ISSUE THREAD

**Issue by dgokcin** [fkirc/skip-duplicate-actions#128]
Hello and thank you for the great project.

What I would like to do is trigger my workflow on push and pull request events but skip the push event if there is an open PR for that branch. I managed to do it with using the version 1.5.1 with the following syntax:
```
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v1.5.1
        with:
          github_token: ${{ github.token }}
          skip_concurrent_trigger: 'push'
```

If this is still possible in this version, what do I need to write. And if this is not possible now why did you removed that functionality and is it OK if I use a previous version.

Thanks!

**Comment by fkirc** [comment]
You can upgrade to v3 and check the updated example in the README.
All functionality is still available in v3, but the concurrent skipping options have been changed.

**Comment by fkirc** [comment]
An equivalent is probably something like `do_not_skip: '["pull_request", "workflow_dispatch", "schedule"]'`, which ensures that pull_request-triggers are never skipped.
Additionally, you might need to choose one of the new concurrent-skipping-options that are listed in the README.

**Comment by dgokcin** [comment]
Thanks, I ended up with using something like this to get the same functionality
```
jobs:
  pre_job:
    # continue-on-error: true # Uncomment once integration is finished
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v3.4.1
        with:
          github_token: ${{ github.token }}
          do_not_skip: '["pull_request", "workflow_dispatch", "schedule"]'
          skip_after_successful_duplicate: false
          concurrent_skipping: 'same_content'
```
