### ISSUE TITLE
skip_after_successful_duplicate not working as expected

### ISSUE THREAD

**Issue by kpturner** [fkirc/skip-duplicate-actions#193]
I am finding that if I have a workflow with two jobs - one a pre-check job that uses this action, and one that gets skipped if it is deemed superflous, then I am finding that the "skip_after_successful_duplicate" is returning true even if the previous job failed.  For example

```
    - name: Concurrency checks
      id: skip_check
      uses: fkirc/skip-duplicate-actions@master
      with:
        concurrent_skipping: 'same_content_newer'
        cancel_others: 'true'
        skip_after_successful_duplicate: 'true'
        do_not_skip: '["workflow_dispatch", "schedule"]'   
```

**Workflow run 1**
pre-job runs successfully
test-job fails

**Workflow run 2**
pre-job runs successfully.  It reports that the same files were run successfully in Workflow run 1
test-job is skipped

Can't work out why.  Unless if is checking a specific job rather than the success of the entire workflow

Might better be illustrated with screen shots:

Workflow 1
![image](https://user-images.githubusercontent.com/308646/152988226-99c35810-0448-4b8a-9da2-6190f99fed0e.png)

If I click on the link given for the successful run I get to here, where the run was clearly not successful
![image](https://user-images.githubusercontent.com/308646/152988421-37a53598-09b9-46b2-93a0-aebc7f7873fc.png)

**Comment by paescuj** [comment]
This happens because you've set [concurrent_skipping](https://github.com/fkirc/skip-duplicate-actions#concurrent_skipping) to "same_content", not because of [skip_after_successful_duplicate](https://github.com/fkirc/skip-duplicate-actions#skip_after_successful_duplicate).

This is a known issue with the "same_content" option and has been addressed with a newer "same_content_newer" option (see #124 and [skip-concurrent-workflow-runs](https://github.com/fkirc/skip-duplicate-actions#skip-concurrent-workflow-runs)).

**Comment by kpturner** [comment]
Firstly many thanks for the quick reply.  However in this case my config for "concurrent_skipping" is already "same_content_newer"

```
    - name: Concurrency checks
      id: skip_check
      uses: fkirc/skip-duplicate-actions@master
      with:
        concurrent_skipping: 'same_content_newer'
        cancel_others: 'true'
        skip_after_successful_duplicate: 'true'
        do_not_skip: '["workflow_dispatch", "schedule"]'   
 ```
