### ISSUE TITLE
Action on pull_request trigger is skipped even though base branch content changed

### ISSUE THREAD

**Issue by fknorr** [fkirc/skip-duplicate-actions#264]
I have the following workflow defined, which enables concurrent skipping and then simply echoes whether a run has been skipped or not.

```yml
name: CI

on:
  push:
  pull_request:

jobs:
  find-duplicate-workflows:
    runs-on: [ self-hosted ]
    steps:
      - id: skip-check
        uses: fkirc/skip-duplicate-actions@v4.0.0
        with:
          concurrent_skipping: "same_content_newer"
          skip_after_successful_duplicate: "true"
      - run: echo ${{ steps.skip-check.outputs.should_skip }}
```

Now I add a new file that only exists in the `main` branch, and an additional file that only exists in a `pr` branch. Now I create a pull request to merge `pr` into `main`. The `push` triggers for both branches are ran as expected.

The `pull_request` triggers must not be skipped however, since the merge will contain both files, so the checked out contents differ from both `main` and `pr`. skip-duplicate-actions however reports `should-skip = true`.

See [our test repo](https://github.com/celerity/test-skip-duplicate-actions) for a reproduction. Runs 6 and 11 are from push events, and 12 is from a `pull_request` trigger concurrent with its sibling `push`.
