### ISSUE TITLE
Add "release" to allowed parameters of do_not_skip

### ISSUE THREAD

**Issue by linkous8** [fkirc/skip-duplicate-actions#272]
The v5 release of this action introduced input validation which is definitely good and appreciated. However, I have found that one of the validations seems to be overtuned (and fallen back to v4 as a temporary remedy). You indicate in documentation that the possible values for `do_not_skip` are pull_request, push, workflow_dispatch, schedule. However, up until this release, I found that using the value of "release" [worked as expected](https://github.com/opsani/servox/actions/runs/2918863969/jobs/4652345237):

```
Run fkirc/skip-duplicate-actions@master
  with:
    concurrent_skipping: same_content
    paths_ignore: ["**/README.md", "**/docs/**", "CHANGELOG.md"]
    do_not_skip: ["pull_request", "workflow_dispatch", "schedule", "release"]
    github_token: ***
    paths: []
    cancel_others: false
    skip_after_successful_duplicate: true
Do not skip execution because the workflow was triggered with 'release'
```

I wanted to bring this up to let you now you should likely add "release" to the values you define for the type WorkflowRunTrigger: https://github.com/fkirc/skip-duplicate-actions/blob/0eb36ff4a0f1eb810a0004a6d25c6b5032df2b27/src/main.ts#L15

Let me know your thoughts and thanks for this most excellent action ❤️
