### ISSUE TITLE
Elements in 'do_not_skip' must be one of "pull_request", "push", "workflow_dispatch", "schedule", "release"

### ISSUE THREAD

**Issue by benshabatnoam** [fkirc/skip-duplicate-actions#274]
Hi,
We're getting this error the first time today and we never changed our yml file.
Could this be because of this PR (https://github.com/fkirc/skip-duplicate-actions/pull/273) that was merged 3 hours ago?
![Snag_280c8b8c](https://user-images.githubusercontent.com/5260028/191818883-6d61ec79-5f97-4a45-af74-78dc9c8cb346.png)

**Comment by benshabatnoam** [comment]
OK, I can confirm 100% sure that this is a v5 error. I just re-run the same commit using v4 and it works...
![Snag_281dd600](https://user-images.githubusercontent.com/5260028/191822244-aa18847e-2ea1-4de5-bcf1-dc979c58c8eb.png)

**Comment by paescuj** [comment]
So what does your `do_not_skip` input look like?

**Comment by benshabatnoam** [comment]
`do_not_skip: '["functions/**", "push", "workflow_dispatch", "schedule"]'`
I guess that's (`functions/**`) not support with v5 anymore?

**Comment by paescuj** [comment]
Hmm, where does `functions/**` come from? As far as I know this is not a valid trigger, see https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows.

**Comment by benshabatnoam** [comment]
I see. So if I got it right, you're saying that the `do_not_skip` key is meant for triggered event?
If so, how can we achieve our original goal to 'do_no_skip' the process once there are changes to the `functions` folder?

**Comment by paescuj** [comment]
> I see. So if I got it right, you're saying that the `do_not_skip` key is meant for triggered event?

Exactly! See also the documentation for the [`do_not_skip` input](https://github.com/fkirc/skip-duplicate-actions#do_not_skip).

> If so, how can we achieve our original goal to 'do_no_skip' the process once there are changes to the `functions` folder?

That depends on your exact goal:
* If you want to run the workflow **only** if there are some changes in the `functions` folder, you can use the [`paths` input](https://github.com/fkirc/skip-duplicate-actions#paths):
  ```yaml
  paths: '["functions/**"]'
  ```

  With this option the workflow will be skipped if there are changes to other files but ones in the `functions` folder or if the exact same files have already been successfully checked in an older run (see https://github.com/fkirc/skip-duplicate-actions#option-3-look-for-successful-checks-of-previous-commits).

* If you want to run the workflow if there are **any** changes (including files in the `functions` folder) you don't need to set any special option because this is already the default behavior of `skip-duplicate-actions`.

* If you want to **never** skip the workflow if there are some changes in the `functions` folder, regardless if the exact same files have already been successfully checked in an older run, you could probably (not tested!) use something like this:
  ```yaml
  pre_job:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
      paths_result: ${{ steps.skip_check.outputs.paths_result }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5
        with:
          skip_after_successful_duplicate: 'false' # Important!
          paths_filter: |
            functions:
              paths:
                - 'functions/**'

  example_job:
    needs: pre_job
    if: '!fromJSON(needs.pre_job.outputs.paths_result).global.should_skip || !fromJSON(needs.pre_job.outputs.paths_result).functions.should_skip'
    # ...
  ```
