### ISSUE TITLE
Reused workflows are not matched for skip_after_successful_duplicate

### ISSUE THREAD

**Issue by li-sumup** [fkirc/skip-duplicate-actions#293]
If the same workflow is being called as a job in another workflow same actions are not recognized as same.

### Setup:
Two workflows ci and cd. cd workflow first step is to include ci step and ci step should be skipped if done before (using [this](https://github.com/fkirc/skip-duplicate-actions#example-1-skip-entire-jobs)). 
```
jobs:

  ci:
    uses: ./.github/workflows/ci.yaml
    secrets: inherit

  cd:
    .....
```
### Outcome:
CI actions executed twice
