### ISSUE TITLE
no_transferable_run with reusable workflow

### ISSUE THREAD

**Issue by AurelienGasser** [fkirc/skip-duplicate-actions#327]
Repro:
- Step 1. Run the reusable workflow with a skippable step: the skippable step is run
- Step 2. Run the reusable workflow with a skippable step: the skippable step is skipped because it was already run in Step 1
- Step 3. Run the caller workflow (which calls the reusable workflow)
- Expected behavior: the skippable job in the called workflow is skipped because it was already run in Step 1.
- Actual behavior: the skippable job in the called workflow is not skipped

Files:
```yaml
# test-child.yaml
name: Test (child)
on:
  workflow_dispatch:
  workflow_call:

permissions:
  actions: write
  contents: read

jobs:
  skip:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5.3.0
        with:
          do_not_skip: '[]'

  actual-work:
    needs: skip
    if: needs.skip.outputs.should_skip != 'true'
    runs-on: ubuntu-latest
    steps:
      - name: hello
        run: echo Hello
```

```yaml
# test-parent.yaml
name: Test (parent)
on:
  workflow_dispatch:

permissions:
  actions: write
  contents: read

jobs:
  call-child:
    uses: <owner_redacted>/<repo_redacted>/.github/workflows/test-child.yaml@<branch_redacted>
```

Workflow runs:

Step 1. 

![image](https://user-images.githubusercontent.com/168382/235141900-0c297149-ceb0-45cd-bee3-d4b6853be260.png)

Step 2.

![image](https://user-images.githubusercontent.com/168382/235141941-2e79986c-5a2c-4d2a-b300-6bd5ce27d6ce.png)

Step 3.

![image](https://user-images.githubusercontent.com/168382/235141992-678cb64e-2b48-458b-b54c-47364cb68ed8.png)
