### ISSUE TITLE
How to use the Cancellation Only mode?

### ISSUE THREAD

**Issue by mwouts** [fkirc/skip-duplicate-actions#33]
Hi there, thanks for the action, it really seems to be what I am looking for (see https://github.com/mwouts/jupytext/issues/605)

I am trying to use the [cancellation only mode](https://github.com/marketplace/actions/skip-duplicate-actions#option-3-cancellation-only).

I have therefore added this step to my jobs:
```
    - name: Skip duplicate actions
      uses: fkirc/skip-duplicate-actions@master
      with:
        github_token: ${{ github.token }}
```

Apparently it successfully detect that some runs are duplicates of others, see for instance [this one](https://github.com/mwouts/jupytext/runs/1169452138?check_suite_focus=true). But the rest of the steps are executed, while I would have expected the run to stop. Did I miss something?
![Screenshot from 2020-09-26 10-07-55](https://user-images.githubusercontent.com/29915202/94336089-9ffaea80-ffe0-11ea-9e84-944e17731cf7.png)
