### ISSUE TITLE
[Feature request] Detect changes in all commits in a pull request

### ISSUE THREAD

**Issue by jbnjohnathan** [fkirc/skip-duplicate-actions#330]
We use this tool only for pull requests and as such we would like to backtrack to include all commits in the specific pull request.
If I understand the config options correctly we need to set a hard number of commits to look back on, rather than have it include all commits in the pull request.

A feature to set this to `all_pr_commits: true` would be really helpful

**Comment by Maxim-Durand** [comment]
You probably found the solution already but for future readers, the easiest solution is to specify a limit to the backtracking  like in the example below : 
```
- id: skip_check
  uses: fkirc/skip-duplicate-actions@v5.3.0
  with:
    paths_filter: |
      your_filter_name:
        paths:
          - 'your_path/**'
        paths_ignore:
          - 'a_different_path/**'
        # This backtracking limit is needed otherwise it will search beyond the PR's commits
        # ${{  github.event.pull_request.commits }} == number of commits in this PR
        backtracking: ${{  github.event.pull_request.commits }}
```
