### ISSUE TITLE
Workflow fails when "do_not_skip" contains "merge_group"

### ISSUE THREAD

**Issue by mbaumanndev** [fkirc/skip-duplicate-actions#332]
Hello,

I have a workflow with the following `do_not_skip` value:

```
do_not_skip: '["workflow_dispatch", "schedule", "merge_group"]'
```

When starting, I get the following error:

```
Error: Elements in 'do_not_skip' must be one of "pull_request", "push", "workflow_dispatch", "schedule", "release"
```

Here is my complete configuration for this action:

```
name: Code checks

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  merge_group:
    branches: [ master ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  queue:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false

    outputs:
      should_skip: ${{ steps.skip.outputs.should_skip }}
      paths_result: ${{ steps.skip.outputs.paths_result }}

    steps:
      - id: skip
        uses: fkirc/skip-duplicate-actions@v5
        with:
          concurrent_skipping: "same_content_newer"
          cancel_others: true
          skip_after_successful_duplicate: true
          do_not_skip: '["workflow_dispatch", "schedule", "merge_group"]'
          paths: '["front/**", "server/**", ".github/workflows/code-checks.yml"]'
          paths_filter: |
            front:
              paths:
                - "front/**"
            server:
              paths:
                - "server/**"
            ci:
              paths:
                - ".github/workflows/code-checks.yml"
```
