### ISSUE TITLE
Option to skip the summry

### ISSUE THREAD

**Issue by ogesaku** [fkirc/skip-duplicate-actions#344]
The summary added in https://github.com/fkirc/skip-duplicate-actions/pull/277 is great for debugging but for most successful runs it's just obsolete making the whole workflow summary less readable. It's also often the first task to run so it takes the space above the fold of the workflow summary.

Could it be disabled via config option or printed only when a job is skipped?

**Comment by fkirc** [comment]
I think it is a good idea, I added the option "skip_summary" with PR https://github.com/fkirc/skip-duplicate-actions/pull/345.

**Comment by ogesaku** [comment]
Thanks for the quick change!

I can see the change was merged but during action execution I still get:
```
Warning: Unexpected input(s) 'skip_summary', valid inputs are ['github_token', 'paths_ignore', 'paths', 'paths_filter', 'cancel_others', 'skip_after_successful_duplicate', 'do_not_skip', 'concurrent_skipping']
```
([Full build log](https://github.com/coditory/actions-release-sample/actions/runs/11280276430/job/31372885849))

Step config:
```
        name: Skip build
        id: skipper
        uses: fkirc/skip-duplicate-actions@v5
        with:
          paths_ignore: '["*.md", ".github/**.md", ".gitignore", "docs/**", "gradle.properties"]'
          skip_summary: true
```
([full config](https://github.com/coditory/actions-release-sample/blob/main/.github/workflows/build.yml#L22))

Do you know when the change will be visible in GitHub actions?
