### ISSUE TITLE
Skip if there are newer runs

### ISSUE THREAD

**Issue by remal** [fkirc/skip-duplicate-actions#69]
I have a quite huge integration test suit and would like to cancel it if at least one newer run is scheduled/in progress.

Is something like this possible?
```yaml
jobs:
  skip_individual_steps_job:
    runs-on: ubuntu-latest
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          cancel_others: 'false'
          concurrent_skipping: 'newer_runs' # <-- a value that makes concurrent skip functionality works only if newer runs exist
      - if: ${{ steps.skip_check.outputs.should_skip != 'true' }}
        run: |
          echo "Run long test suit" & sleep 60
```
