### ISSUE TITLE
[Bug] Both runs cancelled, referencing each other

### ISSUE THREAD

**Issue by tschuchortdev** [fkirc/skip-duplicate-actions#76]
Sorry to bother you again; I just came across this issue where the workflow was triggered twice for a PR (on `push` and `pull_request`) and both runs were canceled, each referencing the other as a duplicate: https://github.com/tschuchortdev/kotlin-compile-testing/pull/84/checks. Could this be a bug or is there a legitimate reason why both runs were cancelled? At this time, the same workflow was also running for other PRs and the branch was force-pushed one minute before the workflow run: https://github.com/tschuchortdev/kotlin-compile-testing/pull/84.

**Comment by fkirc** [comment]
The problem is that you need to configure something like `do_not_skip: '["pull_request", "workflow_dispatch", "schedule"]'`.
This is necessary to explicitly decide whether you want to either skip the `push`-trigger or the `pull_request`-trigger.

Historically, older versions of `skip-duplicate-actions` skipped the `pull_request`-trigger without any additional configuration.
However, some users had a strong requirement to *not* skip the `pull_request`-trigger (because some workflows actually depend on the kind of trigger).
Therefore, modern versions of `skip-duplicate-actions` require an explicit configurtion for "concurrent skipping".

I updated the documentation with https://github.com/fkirc/skip-duplicate-actions/pull/77/files as an attempt to explain it.
Please re-open the issue if it still doesn't work.

**Comment by mbjelac** [comment]
This is not working for me. I marked for not skipping only PRs & schedule because workflow dispatch is the only way I run the workflow. I want to skip a manually triggered workflow if someone starts the workflow again while the same workflow is already running (also triggered manually).

```yaml
  skip-workflow-if-already-started:
    runs-on: ubuntu-latest
    steps:
      - name: skip workflow
        uses: fkirc/skip-duplicate-actions@v5
        with:
          do_not_skip: '["pull_request", "schedule"]'
          concurrent_skipping: always
          skip_after_successful_duplicate: false
```

I started 5-6 of them and they all skipped, each referencing one of the others. I would expect that the workflow with the lowest build number doesn't skip?
