### ISSUE TITLE
Commit skipped because of previously skipped duplicate

### ISSUE THREAD

**Issue by fmigneault** [fkirc/skip-duplicate-actions#90]
I got this workflow: 
https://github.com/crim-ca/weaver/blob/master/.github/workflows/tests.yml

On one later commit in the PR, the check produces: 
https://github.com/crim-ca/weaver/pull/219/checks?check_run_id=1973904249
```
Run fkirc/skip-duplicate-actions@master
  with:
    concurrent_skipping: same_content
    skip_after_successful_duplicate: true
    do_not_skip: ["pull_request", "workflow_dispatch", "schedule", "release"]
    github_token: ***
    paths_ignore: []
    paths: []
    cancel_others: true
Did not find other workflow-runs to be cancelled
Skip execution because the exact same files are concurrently checked in https://github.com/crim-ca/weaver/actions/runs/597418175
```

And that referenced run https://github.com/crim-ca/weaver/actions/runs/597418175 has: 

![image](https://user-images.githubusercontent.com/19194484/109068968-90322000-76be-11eb-97d4-06e984112b1e.png)

So basically, the code was never actually tested.
Is there a way to avoid this issue? Is there something incorrectly configured in the workflow?
https://github.com/crim-ca/weaver/blob/wps-load-cfg/.github/workflows/tests.yml

I have another repo that has similar definition, but somehow I'm not facing the same issues: 
https://github.com/Ouranosinc/Magpie/blob/master/.github/workflows/tests.yml

I'm a bit confused by what might be wrong in this case.

**Comment by hugoh** [comment]
This just happened to me as well. There seems to be a race condition in checking for duplicates.

In my case:
* Workflow 1 running at URL1 said: `Skip execution because the exact same files are concurrently checked in URL2`
* Workflow 2 running at URL2 said: `Skip execution because the exact same files are concurrently checked in URL1`

So, both workflows stopped, and neither fully ran.

**Comment by fkirc** [comment]
I suspect that you might need an additional config like `do_not_skip: ["pull_request", "workflow_dispatch", "schedule"]` or something similar.
In theory, the `do_not_skip`-config should be used to specify which concurrent runs should _not_ be skipped.

**Comment by hugoh** [comment]
@fkirc - I think the problem is that all runs calling `detectConcurrentRuns()` reach the conclusion that there is a `same_content` run and bail out. 1 of them should continue. See #112 as an (untested) proposal to keep the oldest one running. Hopefully I didn't butcher the logic here.

**Comment by fmigneault** [comment]
@hugoh @fkirc  
I gave a try to the new `same_content_newer` from #112 
I'm not sure why my runs are still being skipped, although they both clearly print out they should not skip. Something seems to still behave incorrectly. 

`push`: https://github.com/bird-house/twitcher/pull/106/checks?check_run_id=3447659820
```
Run fkirc/skip-duplicate-actions@master
  with:
    concurrent_skipping: same_content_newer
    skip_after_successful_duplicate: true
    do_not_skip: ["pull_request", "workflow_dispatch", "schedule", "release"]
    github_token: ***
    paths_ignore: []
    paths: []
    cancel_others: false
Did not find any skippable concurrent workflow-runs
Do not skip execution because we did not find a transferable run
```

`pull_request`: https://github.com/bird-house/twitcher/pull/106/checks?check_run_id=3447660041
```
Run fkirc/skip-duplicate-actions@master
  with:
    concurrent_skipping: same_content_newer
    skip_after_successful_duplicate: true
    do_not_skip: ["pull_request", "workflow_dispatch", "schedule", "release"]
    github_token: ***
    paths_ignore: []
    paths: []
    cancel_others: false
Do not skip execution because the workflow was triggered with 'pull_request'
```
