### ISSUE TITLE
Skip concurrent not working

### ISSUE THREAD

**Issue by reinvanimschoot** [fkirc/skip-duplicate-actions#92]
hi guys

I had a quick question.

We just started using this action to make sure we don't get double action runs when pushing and then creating a pull request.
The config we have is the following:

```
    steps:
      - name: Check Duplicate Actions
        id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          concurrent_skipping: 'same_content'
          
          ....
```

Our triggers for the actions are as follows:
```
on: [push, workflow_dispatch, pull_request]
```

Now, with this configuration, we still get a double run when pushing and the creating a pull request. In both logs, I see the following:

```
Run fkirc/skip-duplicate-actions@master
  with:
    concurrent_skipping: same_content
    github_token: ***
    paths_ignore: []
    paths: []
    cancel_others: true
    skip_after_successful_duplicate: true
    do_not_skip: ["workflow_dispatch", "schedule"]
Did not find other workflow-runs to be cancelled
Skip execution because the exact same files are concurrently checked in https://github.com/.../actions/runs/658092745
```

It's a bit confusing since it says it did not find any other workflows to cancel but it also says 'skip execution' which it then doesn't do.

Am I missing a part of the configuration? Are we doing something wrong?

Any help is appreciated!
Cheers
